language: php
php:
  - 5.3.3

env:
  -DB=mysql
before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database if not exists ecne_test;'
  - mysql -e 'use ecne_test; create table if not exists test (id int(11) not null auto_increment, test varchar(20) not null, primary key(id));'
script:
  phpunit --configuration phpunit.xml --coverage-text